@host=http://localhost:9000/api/v1
@employeeApi = {{host}}/employees

### Get All Employees
GET  {{employeeApi}}?page=0&size=10 HTTP/1.1

### Get Employee by id
GET {{employeeApi}}/2 HTTP/1.1

### Delete Employee by id
DELETE {{employeeApi}}?id=9 HTTP/1.1

### Create New Employee
POST {{employeeApi}} HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "age": 23,
  "location": "New Delhi",
  "email": "test@test.com",
  "department": "IT"
}

### Update Employee
PATCH  {{employeeApi}} HTTP/1.1
Content-Type: application/json

{
  "id": 6,
  "name": "Lucky Vishnoi"
}

###
GET  {{employeeApi}}/version HTTP/1.1

### Get Employees By Name
GET {{employeeApi}}/filterByName?name=ram HTTP/1.1


### Get Employees By Name And Location
GET {{employeeApi}}/filterByNameAndLocation?name=priyanshu&location=new delhi HTTP/1.1

### Get Employees By Name Containing Keyword
GET {{employeeApi}}/filterByNameContaining?keyword=u HTTP/1.1

### Get Employees By Name or Location
GET {{employeeApi}}/priyanshu/amroha HTTP/1.1

### Delete Employee by name
DELETE {{employeeApi}}/delete/jack HTTP/1.1